let shopItemsData = [
    {
      id: "Casual_Shirt",
      name: "Casual Shirt",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-1.jpg",
    },
    {
      id: "Office_Shirt",
      name: "Office Shirt",
      price: 100,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-2.jpg",
    },
    {
      id: "T_Shirt",
      name: "T Shirt",
      price: 25,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-3.jpg",
    },
    {
      id: "Mens_Suit",
      name: "Mens Suit",
      price: 300,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-4.jpg",
    },
    {
      id: "Women_Frill_top",
      name: "Women Frill top",
      price: 275,
      desc: " Women Printed regular top with Yoke & Border with Frill Sleeves.",
      img: "images/img-5.webp",
    },
    {
      id: "Power_Shoulders_Top",
      name: "Power Shoulders Top",
      price: 271,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-6.webp",
    },
    {
      id: "croptop",
      name: "WOMEN'S PLAIN CROPTOP",
      price: 365,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-7.webp",
    },
    {
      id: "WOMEN_PLAIN_CROPTOP",
      name: "WOMEN'S PLAIN CROPTOP",
      price: 299,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-8.webp",
    },
    {
      id: "kurta_pyjamas",
      name: "kurta pyjamas",
      price: 345,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-9.webp",
    },
    {
      id: "Girls_Casual_Kurta",
      name: "Girls Casual Kurta",
      price: 650,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-10.webp",
    },
    {
      id: "kurta",
      name: "kids kurta",
      price: 600,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-11.webp",
    },
    {
      id: "kids_kurta",
      name: "kids kurta",
      price: 850,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-12.webp",
    },
  ];
